model:
  name: pixelMar_base_64
  dataset_name: ImageNet
  params:
    img_size: 64
    patch_size: 4
    in_channels: 3
    ema_decay: 0.9995
    t_eps: 1.0e-2
    sample_t_mean: -0.8
    sample_t_std: 0.8
    diffusion_btach_mul: 4
    pred_type: 'v'  
  mae_params:
    encoder_dim: 512
    encoder_depth: 6
    encoder_num_heads: 8
    decoder_dim: 512
    decoder_depth: 6
    decoder_num_heads: 8
    mlp_ratio: 4.0
    dropout: 0.1
    buffer_size: 64
    mask_ratio_min: 0.7
  denoiser_params:
    hidden_dim: 768
    depth: 3
    dropout: 0.1

sampler:
  method: 'heun'
  num_ar_steps: 16
  num_timesteps: 100
  noise_scale: 1.0









  
